/**
 * Consent system (Phase 3, SECURITY.md §4).
 *
 * These operations always require an explicit, per-action confirmation:
 * - Modifying an existing context doc (show diff).
 * - Overwriting AGENTS.md / QWEN.md / CLAUDE.md (show diff; warn if not
 *   PromptForge-created).
 * - Create / write any file under `.promptforge/`.
 *
 * Consent is never remembered across operations. The confirmation
 * callbacks are injected at the UI layer so the service stays testable.
 */

export type ConsentCallback = (
  summary: string,
  detail: string,
  options?: { diff?: string; isOverwrite?: boolean; isForeign?: boolean },
) => Promise<boolean>;

/**
 * File write request with metadata for the consent decision.
 */
export interface FileWriteRequest {
  /** Project-relative path to the file being written (e.g. '.promptforge/context/PRODUCT.md'). */
  absPath: string;
  /** The proposed content. */
  content: string;
  /** Whether a file already exists at this path. */
  exists: boolean;
  /** Whether the existing file was created by PromptForge (via anchor or
   *  template marker). `false` means a foreign/user file. */
  isForeign: boolean;
}

/**
 * Generate a diff preview between existing and proposed content.
 * Simple line-by-line diff for display in the consent dialog.
 */
export function diffPreview(existing: string, proposed: string): string {
  if (existing === '' && proposed === '') return '';
  const existingLines = existing.split('\n');
  const proposedLines = proposed.split('\n');
  const maxLen = Math.max(existingLines.length, proposedLines.length);
  const result: string[] = [];

  for (let i = 0; i < maxLen; i++) {
    const oldLine = existingLines[i] ?? '';
    const newLine = proposedLines[i] ?? '';
    if (oldLine === newLine) {
      result.push(`  ${oldLine}`);
    } else {
      if (oldLine !== '') result.push(`- ${oldLine}`);
      if (newLine !== '') result.push(`+ ${newLine}`);
    }
  }

  return result.join('\n');
}

/**
 * Build a consent summary for writing files during onboarding.
 */
export function fileWriteSummary(requests: FileWriteRequest[]): string {
  const newCount = requests.filter((r) => !r.exists).length;
  const overwriteCount = requests.filter((r) => r.exists).length;
  const parts: string[] = [];
  if (newCount > 0) parts.push(`${newCount} new file${newCount > 1 ? 's' : ''}`);
  if (overwriteCount > 0) parts.push(`${overwriteCount} overwrite${overwriteCount > 1 ? 's' : ''}`);
  return parts.join(', ');
}

/**
 * Categorize a file write as: new, promptforge-owned overwrite, or foreign
 * overwrite (warn distinctly per SECURITY.md §4).
 */
export function categorizeFileWrite(existingContent: string | null): {
  exists: boolean;
  isForeign: boolean;
} {
  if (existingContent === null) return { exists: false, isForeign: false };
  // A file is "PromptForge-owned" if its first line contains the marker.
  const isPromptForge = existingContent.startsWith('# AGENTS.md —')
    || existingContent.startsWith('# Qwen-specific instructions')
    || existingContent.startsWith('@AGENTS.md')
    || existingContent.startsWith('# Product')
    || existingContent.startsWith('# Architecture')
    || existingContent.startsWith('# Design')
    || existingContent.startsWith('# Data Model')
    || existingContent.startsWith('# Integrations')
    || existingContent.startsWith('# Security')
    || existingContent.startsWith('# Testing')
    || existingContent.startsWith('# Decisions')
    || existingContent.startsWith('# Current State')
    || existingContent.startsWith('# Backlog');
  return { exists: true, isForeign: !isPromptForge };
}

/**
 * Marker comment added to PromptForge-generated context files so the
 * consent system can distinguish them from user-created ones.
 */
export const PROMPTFORGE_MARKER = '<!-- Generated by PromptForge Local. Review and edit freely. -->';
